/* U8 · 夜书房书单（预置，零请求）。page＝维基文库原始页名（多为繁体，重定向已跟过）；kind 09-08 逐本核实；
   versions 类给 pick 默认版本。显示名与作者用简体。 */
const BOOKLIST=[
  {title:'红楼梦',author:'曹雪芹',page:'紅樓夢',kind:'subpages',n:120},
  {title:'西游记',author:'吴承恩',page:'西遊記',kind:'subpages',n:100},
  {title:'三国演义',author:'罗贯中',page:'三國演義',kind:'subpages',n:120},
  {title:'水浒传',author:'施耐庵',page:'水滸傳',kind:'versions',pick:'水滸傳 (120回本)'},
  {title:'聊斋志异',author:'蒲松龄',page:'聊齋志異',kind:'subpages',n:12},
  {title:'儒林外史',author:'吴敬梓',page:'儒林外史',kind:'subpages',n:56},
  {title:'老残游记',author:'刘鹗',page:'老殘遊記',kind:'subpages',n:20},
  {title:'镜花缘',author:'李汝珍',page:'鏡花緣',kind:'subpages',n:100},
  {title:'浮生六记',author:'沈复',page:'浮生六記',kind:'subpages',n:6},
  {title:'呐喊',author:'鲁迅',page:'吶喊',kind:'collection'},
  {title:'彷徨',author:'鲁迅',page:'彷徨',kind:'collection'},
  {title:'朝花夕拾',author:'鲁迅',page:'朝花夕拾',kind:'collection'},
  {title:'故事新编',author:'鲁迅',page:'故事新編',kind:'collection'},
  {title:'野草',author:'鲁迅',page:'野艸',kind:'collection'},
  {title:'官场现形记',author:'李宝嘉',page:'官場現形記',kind:'subpages',n:60},
  {title:'二十年目睹之怪现状',author:'吴趼人',page:'二十年目睹之怪現狀',kind:'subpages',n:108},
  {title:'孽海花',author:'曾朴',page:'孽海花',kind:'subpages',n:35},
  {title:'封神演义',author:'许仲琳',page:'封神演義',kind:'subpages',n:100},
  {title:'东周列国志',author:'冯梦龙',page:'東周列國志',kind:'subpages',n:108},
  {title:'三侠五义',author:'石玉昆',page:'三俠五義',kind:'subpages',n:120},
  {title:'儿女英雄传',author:'文康',page:'兒女英雄傳',kind:'subpages',n:40},
  {title:'海上花列传',author:'韩邦庆',page:'海上花列傳',kind:'subpages',n:64},
  {title:'醒世恒言',author:'冯梦龙',page:'醒世恆言',kind:'subpages',n:40},
  {title:'警世通言',author:'冯梦龙',page:'警世通言',kind:'subpages',n:40},
  {title:'喻世明言',author:'冯梦龙',page:'喻世明言',kind:'subpages',n:40},
  {title:'初刻拍案惊奇',author:'凌濛初',page:'初刻拍案驚奇',kind:'subpages',n:40},
  {title:'隋唐演义',author:'褚人获',page:'隋唐演義',kind:'subpages',n:100},
  {title:'说岳全传',author:'钱彩',page:'說岳全傳',kind:'subpages',n:80},
];
